"""add_enhanced_interview_fields

Revision ID: 45a5ee54d2f9
Revises: add_missing_cols
Create Date: 2025-07-29 14:30:27.933634-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a5ee54d2f9'
down_revision = 'add_missing_cols'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preparation_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interview_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_preparation_templates_id'), 'interview_preparation_templates', ['id'], unique=False)
    op.create_index(op.f('ix_interview_preparation_templates_user_id'), 'interview_preparation_templates', ['user_id'], unique=False)
    op.create_table('networking_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('virtual_link', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_hours', sa.String(), nullable=True),
    sa.Column('attendance_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contacts_made', sa.String(), nullable=False),
    sa.Column('follow_ups_required', sa.String(), nullable=False),
    sa.Column('opportunities_identified', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networking_events_id'), 'networking_events', ['id'], unique=False)
    op.create_index(op.f('ix_networking_events_user_id'), 'networking_events', ['user_id'], unique=False)
    op.create_table('status_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('auto_transition', sa.String(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_rules_id'), 'status_rules', ['id'], unique=False)
    op.create_index(op.f('ix_status_rules_user_id'), 'status_rules', ['user_id'], unique=False)
    op.create_table('contact_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('interaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_completed', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('led_to_opportunity', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_interactions_contact_id'), 'contact_interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_interactions_id'), 'contact_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_contact_interactions_job_application_id'), 'contact_interactions', ['job_application_id'], unique=False)
    op.create_table('interview_checklist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('estimated_time_minutes', sa.String(), nullable=True),
    sa.Column('order_index', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['interview_preparation_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_checklist_items_id'), 'interview_checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_interview_checklist_items_template_id'), 'interview_checklist_items', ['template_id'], unique=False)
    op.create_table('status_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('transition_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_transitions_id'), 'status_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_status_transitions_job_application_id'), 'status_transitions', ['job_application_id'], unique=False)
    op.create_table('interview_preparations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('time_spent_minutes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['interview_checklist_items.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_preparations_checklist_item_id'), 'interview_preparations', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_interview_preparations_id'), 'interview_preparations', ['id'], unique=False)
    op.create_index(op.f('ix_interview_preparations_interview_id'), 'interview_preparations', ['interview_id'], unique=False)
    op.drop_index('ix_achievements_category', table_name='achievements')
    op.drop_index('ix_achievements_unlocked', table_name='achievements')
    op.drop_index('ix_achievements_user_id', table_name='achievements')
    op.add_column('contacts', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('preferred_contact_method', sa.String(), nullable=False))
    op.add_column('contacts', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('preparation_notes', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('questions_asked', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('questions_to_ask', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('technical_topics', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('follow_up_required', sa.Boolean(), nullable=False))
    op.add_column('interviews', sa.Column('follow_up_sent', sa.Boolean(), nullable=False))
    op.add_column('interviews', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('communication_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('technical_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('cultural_fit_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('difficulty_level', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('would_recommend_company', sa.Boolean(), nullable=True))
    op.drop_index('ix_job_applications_user_applied_date', table_name='job_applications')
    op.drop_index('ix_job_applications_user_status', table_name='job_applications')
    op.drop_index('ix_streaks_user_date', table_name='streaks')
    op.drop_index('ix_streaks_user_goal_met', table_name='streaks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_streaks_user_goal_met', 'streaks', ['user_id', 'goal_met'], unique=False)
    op.create_index('ix_streaks_user_date', 'streaks', ['user_id', 'date'], unique=False)
    op.create_index('ix_job_applications_user_status', 'job_applications', ['user_id', 'status'], unique=False)
    op.create_index('ix_job_applications_user_applied_date', 'job_applications', ['user_id', 'applied_date'], unique=False)
    op.drop_column('interviews', 'would_recommend_company')
    op.drop_column('interviews', 'difficulty_level')
    op.drop_column('interviews', 'cultural_fit_rating')
    op.drop_column('interviews', 'technical_rating')
    op.drop_column('interviews', 'communication_rating')
    op.drop_column('interviews', 'follow_up_date')
    op.drop_column('interviews', 'follow_up_sent')
    op.drop_column('interviews', 'follow_up_required')
    op.drop_column('interviews', 'technical_topics')
    op.drop_column('interviews', 'questions_to_ask')
    op.drop_column('interviews', 'questions_asked')
    op.drop_column('interviews', 'preparation_notes')
    op.drop_column('contacts', 'timezone')
    op.drop_column('contacts', 'preferred_contact_method')
    op.drop_column('contacts', 'tags')
    op.create_index('ix_achievements_user_id', 'achievements', ['user_id'], unique=False)
    op.create_index('ix_achievements_unlocked', 'achievements', ['unlocked'], unique=False)
    op.create_index('ix_achievements_category', 'achievements', ['category'], unique=False)
    op.drop_index(op.f('ix_interview_preparations_interview_id'), table_name='interview_preparations')
    op.drop_index(op.f('ix_interview_preparations_id'), table_name='interview_preparations')
    op.drop_index(op.f('ix_interview_preparations_checklist_item_id'), table_name='interview_preparations')
    op.drop_table('interview_preparations')
    op.drop_index(op.f('ix_status_transitions_job_application_id'), table_name='status_transitions')
    op.drop_index(op.f('ix_status_transitions_id'), table_name='status_transitions')
    op.drop_table('status_transitions')
    op.drop_index(op.f('ix_interview_checklist_items_template_id'), table_name='interview_checklist_items')
    op.drop_index(op.f('ix_interview_checklist_items_id'), table_name='interview_checklist_items')
    op.drop_table('interview_checklist_items')
    op.drop_index(op.f('ix_contact_interactions_job_application_id'), table_name='contact_interactions')
    op.drop_index(op.f('ix_contact_interactions_id'), table_name='contact_interactions')
    op.drop_index(op.f('ix_contact_interactions_contact_id'), table_name='contact_interactions')
    op.drop_table('contact_interactions')
    op.drop_index(op.f('ix_status_rules_user_id'), table_name='status_rules')
    op.drop_index(op.f('ix_status_rules_id'), table_name='status_rules')
    op.drop_table('status_rules')
    op.drop_index(op.f('ix_networking_events_user_id'), table_name='networking_events')
    op.drop_index(op.f('ix_networking_events_id'), table_name='networking_events')
    op.drop_table('networking_events')
    op.drop_index(op.f('ix_interview_preparation_templates_user_id'), table_name='interview_preparation_templates')
    op.drop_index(op.f('ix_interview_preparation_templates_id'), table_name='interview_preparation_templates')
    op.drop_table('interview_preparation_templates')
    # ### end Alembic commands ###