"""Add location_type and salary_info fields

Revision ID: 4f20e981e1fe
Revises: add_salary_text_only
Create Date: 2026-01-07 21:52:47.276505-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f20e981e1fe'
down_revision = 'add_salary_text_only'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'headquarters')
    op.drop_column('companies', 'founded_year')
    op.add_column('job_applications', sa.Column('location_type', sa.String(), nullable=True))
    op.add_column('job_applications', sa.Column('salary_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'salary_info')
    op.drop_column('job_applications', 'location_type')
    op.add_column('companies', sa.Column('founded_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('headquarters', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###